CREATE TABLE User (
  "id" INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
  "username" VARCHAR(32) NOT NULL,
  "password" VARCHAR(255) NOT NULL,
  "desc" TEXT NOT NULL DEFAULT(''),
);

CREATE TABLE Message (
  "from" INT UNSIGNED NOT NULL,
  "to" INT UNSIGNED NOT NULL,
  "value" TEXT NOT NULL,
  "delivered" BOOLEAN NOT NULL DEFAULT(false),
  "read" BOOLEAN NOT NULL DEFAULT(false),
);